language: python

python:
- "2.7"

install:
- pip install pip setuptools
- pip install -U pip setuptools
- pip install ansible-lint
- ansible-galaxy install -r requirements.yml -p roles

script:
# show the ansible-lint version
- ansible-lint --version
# TODO: fix the line length ignore
- ansible-lint packer-setup.yml -x 204
- ansible-lint main.yml -x 204
