---
- name: set registry flag that shows updates for compatible anti-viruses
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\QualityCompat
    name: cadca5fe-87d3-4b96-b7fb-a231484277cc
    data: 0
    type: dword

- name: enable verbose logging (WUA seems to fail on some installs without this)
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Trace
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  loop:
  - name: Flags
    data: 7
  - name: Level
    data: 4

# This is a pretty ugly hack as there is no do until over a block of tasks. This
# will loop over the update and reboot task 10 times to cover all updates, the
# tasks in the loop are skipped when there are no updates which leads to a very
# minimal loss of time when all the updates are installed and we are still
# looping.
# We also set a dict that contains each category we loop through and whether we
# have exhausted the updates for the respective category. This is only done
# win_updates sometimes fails when too many updates need to be installed. This
# way each update block is split into smaller chunks.
- name: set initial update_stat fact
  set_fact:
    update_stat:
    - name: CriticalUpdates
      finished: False
    - name: SecurityUpdates
      finished: False
    - name: Updates
      finished: False
    - name: UpdateRollups
      finished: False
    - name: FeaturePacks
      finished: False

- include_tasks: update.yml
  loop: [1, 2, 3, 4, 5, 6, 7, 8, 9, 'end']
  loop_control:
    loop_var: loop_number

- name: remove verbose Windows Update logging
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Trace
    state: absent
    delete_key: yes

- name: stop the Windows Update service
  win_service:
    name: wuauserv
    state: stopped

- name: clear update log after it blew up from the above
  win_file:
    path: C:\Windows\WindowsUpdate.log
    state: absent
  ignore_errors: yes

- name: start the Windows Update service
  win_service:
    name: wuauserv
    state: started
