---
# run our customised update task for each category
- name: install updates - round {{ loop_number }}
  include_tasks: update_task.yml
  loop: '{{ update_stat }}'
  loop_control:
    loop_var: category_info

- name: run final update task at the end in case we missed anything
  win_updates:
    category_names: '{{ update_stat|categories_to_list }}'
    state: installed
  register: pri_update_final
  when: loop_number == 'end'

- name: reboot after final update task
  win_reboot:
    reboot_timeout: 1200
  when:
  - pri_update_final.reboot_required is defined
  - pri_update_final.reboot_required
