---
- name: run ngen to recompile .NET assemblies
  win_dotnet_ngen:

- name: ensure unattend panther and temp directory exists
  win_file:
    path: '{{item}}'
    state: directory
  loop:
  - C:\Windows\Panther\Unattend
  - C:\temp

- name: create PackerWindoze PowerShell module folder
  win_file:
    path: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze
    state: directory

- name: copy across the PackerWindoze manifest file
  win_copy:
    src: PackerWindoze.psm1
    dest: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze\PackerWindoze.psm1

- name: template across the PackerWindoze definition file
  win_template:
    src: PackerWindoze.psd1
    dest: C:\Program Files\WindowsPowerShell\Modules\PackerWindoze\PackerWindoze.psd1

- name: make sure module path is added to PSModulePath
  win_path:
    name: PSModulePath
    scope: machine
    state: present
    elements: C:\Program Files\WindowsPowerShell\Modules

- name: template the unattend.xml file
  win_template:
    src: unattend.xml.tmpl
    dest: C:\Windows\Panther\Unattend\unattend.xml

- name: copy across the sysprep powershell script
  win_template:
    src: setup.ps1.tmpl
    dest: C:\temp\setup.ps1

- name: create scheduled task to delete WinRM listeners and shutdown
  win_scheduled_task:
    name: packer-shutdown
    username: SYSTEM
    disallow_start_if_on_batteries: no
    stop_if_going_on_batteries: no
    actions:
    - path: powershell.exe
      arguments: Remove-Item -Path WSMan:\localhost\Listener\* -Recurse -Force
    - path: C:\windows\system32\sysprep\sysprep.exe
      arguments: /generalize /oobe /quiet /shutdown /unattend:C:\Windows\Panther\Unattend\unattend.xml

- name: set flag to recreate pagefile after next sysprep
  win_shell: |
    $system = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
    if ($system -ne $null) {
        $system.AutomaticManagedPagefile = $true
        $system.Put()
    }

- name: 0 out empty space for later compression
  win_shell: |
    $path = "C:\zero"
    $volume = Get-WmiObject -Class Win32_LogicalDisk -Filter "DeviceID='C:'"
    $block_size = 64kb
    $leftover_size = $volume.Size * 0.05
    $file_size = $volume.FreeSpace - $leftover_size
    $data_array = New-Object -TypeName byte[]($block_size)

    $stream = [System.IO.File]::OpenWrite($path)
    try {
        $current_file_size = 0
        while ($current_file_size -lt $file_size) {
            $stream.Write($data_array, 0, $data_array.Length)
            $current_file_size += $data_array.Length
        }
    } finally {
        if ($stream) {
            $stream.Close()
        }
    }
    Remove-Item -Path $path -Force | Out-Null
